In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [12]:
iris=load_iris()

In [13]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

LogisticRegression

In [14]:
Logistic_score=cross_val_score(LogisticRegression(),iris.data,iris.target)
Logistic_score

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [15]:
np.average(Logistic_score)

0.9733333333333334

Decision tree

In [16]:
Decision_tree=cross_val_score(DecisionTreeClassifier(),iris.data,iris.target)
Decision_tree

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [17]:
np.average(Decision_tree)

0.9600000000000002

Svm

In [18]:
svm=cross_val_score(SVC(),iris.data,iris.target)
svm

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [19]:
np.average(svm)

0.9666666666666666

Random Forest

In [20]:
Random_score=cross_val_score(RandomForestClassifier(),iris.data,iris.target)
Random_score

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [21]:
np.average(Random_score)

0.9666666666666668